create table project_code
(
    project_id   varchar(7)   not null
        primary key,
    project_name varchar(100) null,
    salesperson  varchar(30)  null
);

INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C0', 'BioMed', 'No salesperson');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C1', 'Wecare Mask HK', 'Anthony Tso');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C10', 'Children’s Hospital', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C100', 'Prestige Medical Centre Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C101', 'Laboratory for AI-Powered (Prof. Houmin Yan)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C102', 'Virtus (Prof. Sing Lee)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C103', 'The International Medical Co Ltd', 'Alex & Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C104', 'New World (Eureka nova)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C105', 'Restore Integrative Medical Clinic PTE', 'Gordon & Rex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C106', 'Central Gastroenterology & Hepatology Centre (Dr. Ernest Li)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C107', 'Weybridge (Dr. Derek Lee)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C108', 'AMG Health Check Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C109', '123 Clinic (Plaza 88)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C11', 'Prince of Wales Hospital', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C110', 'Asia Pacific (Dr. Chung Ho Fai)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C111', 'Virtus (Denise Tam)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C112', 'Virtus (Yvonne Lam)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C113', 'Virtus (Dr. Stanley Lo)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C114', 'Virtus (Felix Chan) Sample', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C115', 'Virtus (Felix Chan)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C116', 'M12 Sample', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C117', 'Joyland Medical Centre', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C118', 'BMS Clinic Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C119', 'Absolute Apex+ Medical Centre', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C12', '便利醫 Easy Healthcare', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C120', 'Mint Dietitian Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C121', '星光行 health vision', 'Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C122', 'BioMed Healthy Square', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C123', 'Hong Kong Eczema Center Limited', 'Terry Lam');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C124', 'Virtus (Dr. Ho Yung Yung)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C125', 'Virtus (Dr. Chu Chung Ming)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C126', 'UST Clinic', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C127', 'Bowtie & JP', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C128', 'Virtus (Ernest Tsoi)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C129', 'Medickind Company Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C13', 'Prohab 金鐘', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C130', 'Neo-Health Group', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C131', 'Dr. Signature (Tailormade)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C132', 'Food Medic', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C133', 'HEAL Oncology (Dr. Henry Sze)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C134', 'AMG (TST)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C135', '美邦 (佐敦)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C136', 'Prime Family Health Limited', 'Genevieve');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C137', 'Virtus (Dr. Francis Li)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C138', 'Solution Care (Michelle Lau)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C139', 'Wellness Treasure', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C14', 'Kinetics medical', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C140', 'Chain\'s', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C141', 'BMU', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C142', 'Central Health', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C143', 'FWD Life Insurance Company (Bermuda) Limited', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C144', 'Deep Blue Health HK Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C145', 'Medicsure group (Dr. Ip Ka Lun)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C146', 'Beyond Horizon Women Care Center', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C147', 'Fountain Perfect Union Medical Ltd.', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C148', 'Beyond Horizon Women Care Centre ', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C149', 'Beyond Horizon Anti-aging Centre ', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C15', 'Pangenia Inc', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C150', 'Hong Kong Howan Mall Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C151', 'Good Vision International Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C152', 'SK Care Specialist Limited', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C153', 'CEMG (2023 annual Din)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C154', 'CUHK 60 Anni', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C155', 'S & C Global Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C156', 'APEX DNA diagnostic laboratory medical group limited (MK)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C157', 'Fit Fit Food Nutrition ', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C158', 'Dr Chan Wai Chung\'s Clinic Co. Limited', 'Genevieve');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C159', 'Hong Kong Howan Mall Limited (Staff plan) ', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C16', 'Wederm', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C160', 'New Always Beauty Salon Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C161', 'Family Medical Practice Gba Limited (Dr. 李國棟)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C162', 'Central Health Medical Practice (Dr Dede Chan)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C163', 'JAC Nutrition and Fitness Consultancy', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C164', 'Asia Medical Specialists Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C165', 'DP Place Limited (Dr. Pura Cheng)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C166', 'Clearbridge', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C167', 'UE Chinese Medicine', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C168', 'Wise Group (Michael)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C168-1', 'Wise Group (Lei King Wan Shop)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C168-2', 'Wise Group (Central Caine Road Shop)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C168-3', 'Wise Group (East Point City Shop)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C168-4', 'Wise Group (Happy Valley Shop)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C169', '明德中醫診所', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C17', 'Achoice', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C170', 'Papa Innovation Company', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C171', 'Precision Health & Diagnostic Centre ', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C172', 'HEAL Oncology Centre (Dr. Henry  Sze)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C173', 'Mei Foo Veterinary Hospital', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C174', 'Omnicare Pain Centre Limited (李旭明醫生)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C175', 'PSG Vivet Company Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C175-01', 'PSG pet pre-test', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C175-02', 'PSG pet post-test', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C176', 'The Pet Specialist Co. Limited ', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C177', 'Ace Wellness Ltd', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C178', 'Life Young Healthcare Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C179', 'Ammahage Limited', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C18', 'Smile and Face Medical Group', 'Terry Lam');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C180', 'Coffee Obsession Limited', 'Terry Lam');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C181', 'Gardenia Medical Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C182', 'Zenith medical Centre (TST-孫錫鴻醫生)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C183', 'Prof. Gary Tse (MU)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C184', 'Horizon HealthCare', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C185', 'Shalom Medical Center', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C186', 'Dr Li Ching Kwok Rico', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C187', 'EC healthcare', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C188', 'Dr. Victor TL Wong Medical Clinic', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C189', 'Virtus Heart Clinic Limited (Dr. Adrian Cheong)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C19', 'Enas Wellness Limited', 'Terry Lam');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C190', 'Victory Sealion Medical Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C191', 'Femina Healthcare Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C192', 'Family Medical Centre (Tin Shui Wai)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C193', 'The Specialist (Dr. Lam)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C194', 'Pricerite Pet Necessities Ltd', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C195', 'Yitin Limited (Dr. Chen Yi Tin)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C196', 'New Town Medical & Dental Services Limited (Dr. Steve Kwok Keung Wu)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C197', 'Immu-Health Wellness Company (Vincent Yeung)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C198', 'Dr. Li Chi Him', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C199', 'BMI Innovation Ltd', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C2', 'Vitality Centre', 'Anthony Tso');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C20', 'APEX (Shek Mun)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C200', 'Health Care Signature (CWB Pain Management Centre)', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C201', 'Health Care Signature (Mongkok Pain Management Centre)', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C202', 'Mobicares Innovation Limited', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C203', '明德中醫診所', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C204', 'Intuitive Technology Limited (Thomas K.F.Lau)', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C205', 'Hong Kong Endoscopic & Laparoscopic Surgery Centre Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C206', 'Elite Healthcare Limited  ', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C207', 'Madame Champagne Limited (Thrive Wellness)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C208', 'Health Yourself Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C209', 'Beacon Medical Centre', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C21', 'Mixx Collection Ltd', 'No salesperson');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C210', 'Perfect Integrated Health Company Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C211', 'Ortus Bloom', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C212', 'Tetra Nutritional Consultation Centre Company Ltd', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C213', 'Faith Healthcare Centre', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C214', 'ONIE COMPANY LIMITED', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C215', 'Great China Health Association', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C216', 'Hong Kong Thyroid & Endocrine Surgery Centre', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C217', 'Yobo Technology Limited (eefit)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C218', 'P&P Medical Center', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C219', 'Dr. Yeung Hoi Pun\'s Clinic', 'Mabel');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C22', 'Life Clinic', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C220', 'SC Medical Center', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C221', 'Mindful Genomics Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C222', 'YATA CRM campaign', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C223', 'Manulife (Dick Wong District)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C224', 'CMEDICA Clinical Centre', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C225', '源青一堂 Arche Touch Limited', 'Rex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C226', 'Oxford University Press', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C227', 'Medicare health clinic limited - DR . YUEN MING WAI', 'Mabel');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C227-1', 'Medicare health clinic limited - Dr. Tang Man Ho', 'Mabel');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C228', 'Mandala Medical Education Limited', 'Rex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C229', 'Swangi Co. Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C23', 'VNV Medical', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C230', 'Humansa VD Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C231', 'Blck Healthcare Technology Company', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C232', 'BNI clients', 'Rex Gordon Eddie');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C233', 'C Live Online Limited', 'Rex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C234', 'Mobile Medical & Health Check Centre Limited', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C235', 'Brighten Technology Limited', 'Gordon Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C236', 'Exercise Prescription Limited', 'Rex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C24', 'Balance Health', 'Joseph and Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C25', 'Prohab 荃灣', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C26', 'Prohab 旺角', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C27', 'Optimal Health', 'Joseph and Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C28', 'Zenith TST', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C29', '栢峰 (荃灣 UG51)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C3', 'SH', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C30', '栢峰 (沙田 806)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C31', '栢峰 (沙田 606)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C32', '栢峰 (尖沙咀 H Zentre)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C33', 'LTADHD', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C34', 'BDMS (Thailand)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C35', 'Hong Kong Bright Medical Co., Ltd', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C36', 'Rambo Medical Center', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C37', '百本', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C38', 'Fatology Company Limited', 'Terry Lam');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C39', '護你站', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C4', 'CASH Group', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C40', '一同夢 (Autism)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C41', '源青一堂', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C42', 'Health Online Solution', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C43', 'SH (Tailormade)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C44', 'Mead Johnson', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C45', 'See Way', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C46', '仁信堂', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C47', 'SHLD', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C48', '正元中醫', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C49', '123 Clinic', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C5', 'Thailand', 'No salesperson');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C50', 'SH (Sample)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C51', 'Choy Sum Health', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52', 'Health Care Signature', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52-1', 'Health Care Signature_Causeway Bay', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52-2', 'Health Care Signature_Hung Hom', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52-3', 'Health Care Signature_Sheung Shui', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52-4', 'Health Care Signature_Tsim Sha Tsui', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C52-5', 'Health Care Signature_Mong Kok', 'Philip');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C53', 'HK01', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C54', 'Trustnheal', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C55', 'Bonum', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C56', 'Archetouch New World', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C57', '樂活人生', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C58', 'SH OB610', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C59', 'ACECGT', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C6', 'Bonjour 卓悅', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C60', 'Yau Tat Construction Company Limited', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C61', 'CIC 源青', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C62', 'CEMG (Sha Tin)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C63', 'CEMG (Aberdeen)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C64', 'CEMG (World Trade)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C65', 'CEMG (Tsim Sha Tsui)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C66', 'CEMG (Mong Kok)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C67', 'JP Partners Medical (Mong Kok)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C68', 'JP Partners Medical (Tuen Mun)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C69', 'Expo Medical Centre', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C7', 'Tai On International Consultancy Ltd 泰安國際顧問有限公司', 'Anthony Tso');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C70', 'Children 1st Paediatric Clinic', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C71', '信康 (大埔)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C72', '信康 (旺角)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C73', 'Icon Cancer Centre', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C74', '519 Clinic', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C75', 'I-med', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C76', 'Archiater Medical', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C77', 'BMI Funds', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C79', 'Spring Family (江永明醫生)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C8', 'MediFast', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C80', 'Virtus (Dr. Chow Chung Mo)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C81', 'Dr. Sit Sou Chi', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-0', 'Human Health (Kowloon Bay)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-1', 'Human Health (Tsuen Wan)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-10', 'Human Health (LOHAS Park)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-11', 'Human Health (Tsing Yi)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-12', 'Human Health (Tseung Kwan O - 將軍澳中心)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-13', 'Human Health (Kwun Tong)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-14', 'Human Health (Tiu Keng Leng)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-15', 'Human Health (Hang Hau)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-16', 'Human Health (Tseung Kwan O - 海悅豪園商場)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-17', 'Human Health (Po Lam)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-18', 'Human Health (Jordan - 明珠廣場 1,3/F)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-19', 'Human Health (樂善堂)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-2', 'Human Health (Sai Wan Ho)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-20', 'Human Health (Kowloon)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-21', 'Human Health (Tuen Mun)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-22', 'Human Health Medical Centre (Quarry Bay)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-23', 'Impact Medical Imaging Centre', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-24', 'Human Health (Tai Wai)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-25', 'Human Health Integrated Medical Centre (Sheung Shui)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-26', 'Human Health (Kwun Tong - Po Tat Shopping Centre)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-27', 'Human Health (Yau Tong)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-28', 'Human Health (Yuen Long)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-29', 'Human Health (Kwai Fong)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-3', 'Human Health (Tung Chung)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-4', 'Human Health (Hung Hom)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-5', 'Human Health (Lai Chi Kok)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-6', 'Human Health (Tseung Kwan O)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-7', 'Human Health (Jordan - 明珠廣場 3/F)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-8', 'Human Health (Shau Kei Wan)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C82-9', 'Human Health (Tin Shui Wai)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C83', 'Obelle (Dr. Lam Long Yan Kelvin)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C84', 'Ansen Health Care Center', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C85', 'To Love Wedding', 'Terry');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C86', 'Adventist Medical Center (Quarry Bay)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C87', '信康 (佐敦)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C88', 'Walka Technology Co.', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C89', 'Cantab Medical', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C9', 'HKHS', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C90', 'Alibaba', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C91', 'Swindon', 'Joseph and Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C92', 'Hong Kong Adventist Hospital (Stubbs Road/TW)', 'Genevieve');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93', 'Wellmind', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-1', 'Wellmind (FFFJ)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-10', 'Wellmind-CaLe', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-11 ', 'Wellmind-WD', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-12 ', 'Wellmind KSP', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-13', 'Wellmind HGW', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-14', 'Wellmind GPS', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-15', 'Wellmind GX', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-16', 'Wellmind MHC', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-17', 'Wellmind SCMC', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-18', 'Wellmind PEU', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-2', 'Wellmind (FFFKT)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-3', 'Wellmind-HWS', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-4', 'Wellmind-JD', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-5', 'Wellmind-AL', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-6', 'Wellmind-CM', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-7', 'Wellmind-CS', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-8', 'Wellmind-DPC', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C93-9', 'Wellmind-CaLi', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C94', 'CEMG (Watson’s) Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C95', 'Solution Care', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C96', 'Omega International Health Service', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C97', 'HypnoHealth Consulting Limited', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C98', 'Mind Healing Centre', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('C99', 'Transcend', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('O2', 'IgE pilot test, Tsuen Wan samples', '');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('O3', 'IgE pilot test, Yuen Long samples', '');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P1', 'Marketing survey (Oct 20)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P10', 'PRC JD Survey (2nd)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P11', 'PrimeCare MK', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P12', 'Dr. So Tsz Him', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P13', 'Terry Lam', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P14', 'CUHK AD 2020', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P15', 'BB Expo 2020', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P16', '保誠Gordon', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P17', 'BB Expo 2021', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P18', 'CUHK Chronic urticaria 2021', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P19', 'Tailor Made', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P2', 'Marketing Research (Dec 20)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P20', 'PrimeCare TST', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P21', 'Dr. Lam Mei, May', 'Terry');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P22', 'APEX (Matthew)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P23', 'Paedicare (Dr. So Wing Yee)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P24', 'Hesita Medical Centre (吳澤銓醫生)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P25', '天一醫務所 (Terence Chow)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P26', 'Health Expo 2021', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P27', 'GeneX (Dabby Lo)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P28', '香港先生 (Rocky)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P29', '王夢貞醫生', 'Joseph and Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P3', 'Marketing Research Mood Survey (May)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P30', '友邦醫療中心 (翁志羽)', 'Joseph and Gordon');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P31', '浸會醫院 (鄧妙詩醫生)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P32', 'DCCT', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P33', 'CUHK Depression Intervention 2022', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P34', 'CUHK Skin 2022', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P35', 'Primecare (Central)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P36', 'Prohab Event', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P37', 'Wellmind Seminar', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P38', 'Dr. Stephanie Chow (Central)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P39', 'CUHK RCMARa', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P4', 'HK Psorisis Survey (1st)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P40', 'Dr. Norman Chan', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P41', 'Vepro (Dr. Lau Shing Chi Steve)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P42', 'Dr. Stephanie Chow (MongKok)', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P43', 'CUHK MHLJDD AD', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P44', 'Dr. Ho King Man', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P45', 'Dr Milton Lo', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P46', '信康姑娘 (大埔)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P47', '信康姑娘 (旺角)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P48', '信康姑娘 (佐敦)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P49', 'CEMG (Sample)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P5', 'HK Kids Allergy Survey (1st)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P50', 'BMI Xmas', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P51', 'BMI Client', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P52', 'Dr. Alex Lai', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P53', 'Gobi (HSBC LP)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P54', 'CUHK Psoriasis (Shuiniujiao Dihuang Decoction)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P55', 'CUHK Psoriasis (Novel Chinese Medicine Formula)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P56', 'CUHK Chronic Pharyngitis', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P57', 'VIP - Kary Ng', 'Heidi');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P58', 'VIP - Miss Ying', 'Steve Wong');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P59', 'SH (PRC)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P6', 'HK Psorisis Survey (1st)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P60', 'CEMG (CWB DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P61', 'CEMG (TST DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P62', 'CEMG (MK DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P63', 'CEMG (Shatin DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P64', 'CEMG (Aberdeen DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P65', '信康 (大埔 DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P66', '信康 (旺角 DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P67', 'Oral Microbiome Marketing Research', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P68', 'CEMG (Staff)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P69', 'Asia Pacific (DS)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P7', 'HK Mood Survey (2nd)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P70', 'AMG (Staff)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P71', 'AMG (Staff - Shatin)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P72', 'AMG (Staff - TST)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P73', 'Consultation team', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P74', '陽普', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P75', '精科', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P76', 'CEMG (staff plan R2)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P77', 'BMU (staff plan)', 'Joseph Tsui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P78', 'MOS Internal Trial', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P79', 'B to C Tailormade program', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P8', 'HK Psorisis Survey (2nd)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P80', 'Pet Space Show', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P81', 'Pet Show Stool Sample', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P82', 'PET-A-HOOD Pet Package  (test + 2 probiotics)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P83', 'BB Expo 2024', 'Alex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P85', 'Vegetarian Food Expo 2024', 'Alex');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P85-01', 'PSG for sales pre-test (test + 3 probiotics)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P85-02', 'PSG for sales post-test  (test + 3 probiotics)', 'Ben Hui');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P87-01', 'Pet for R&D pre-test (test + 3 probiotics)', 'Claudia');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P87-02', 'Pet for R&D post-test  (test + 3 probiotics)', 'Claudia');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P88', 'Pet Stool (Report Only)', 'Claudia');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P89', 'SOGO (Spring + Sakura Theme Promotion)', 'Sale site');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P9', 'PRC JD Survey (1st)', 'unknow');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P90', 'In home Expo', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P91', 'Health Expo', 'Alex Tsang');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P92', 'HKSTP-Booth-May 2024', 'Sales Team');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P93', '2024 50+ Expo', 'Sales Team');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P94-01', 'Pet Research 2 pre-test', 'Ben Hui / Claudia');
INSERT INTO biomed_db.project_code (project_id, project_name, salesperson) VALUES ('P94-02', 'Pet Research 2 post-test', 'Ben Hui / Claudia');
